name: Update blog posts and StackOverflow activity

on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day, at 00:00 UTC
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through Github > Actions > Workflows

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/davenull311"
          max_post_count: 3
          template: $title $newline $description
  
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://stackoverflow.com/feeds/user/9586535"
